# Generated by Django 5.0.4 on 2024-04-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('continent_id', models.AutoField(primary_key=True, serialize=False)),
                ('continent_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('under_title', models.CharField(max_length=90)),
                ('content', models.TextField()),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.continent')),
            ],
        ),
    ]
