# Generated by Django 5.0.4 on 2024-04-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_continent_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='continent',
            table='continent',
        ),
    ]
